### ISSUE TITLE
TypeError: argument 'files': 'WordPieceTrainer' object cannot be converted to 'Sequence'

### ISSUE THREAD

**Issue by TirthankarcIHX** [georgianpartners/Transformers-Domain-Adaptation#22]
Hi, while trying to create new tokens from my data and add them to the tokenizer of "emilyalsentzer/Bio_ClinicalBERT" I'm getting this error message. 
![Screenshot 2023-05-18 122515](https://github.com/georgian-io/Transformers-Domain-Adaptation/assets/122451818/f732572c-fc32-4c8a-a4c5-5ca2be96dded)

**Comment by dluongo9** [comment]
I'm having the same issue here.
